import { type Listing } from '@/types/listing'

export const DUMMY_LISTINGS: Listing[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // CARS (28 Listings across tiers, makes, conditions, & states)
  // ─────────────────────────────────────────────────────────────────────────
  {
    _id: 'car-1',
    _type: 'listing',
    _createdAt: '2026-08-15T10:00:00Z',
    title: '2021 Lexus RX 350 F-Sport (Foreign Used)',
    slug: { current: '2021-lexus-rx-350-f-sport' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-1', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [
      { _type: 'image', asset: { _ref: 'img-c1-1', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80' },
      { _type: 'image', asset: { _ref: 'img-c1-2', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80' },
    ],
    description: `Immaculate 2021 Lexus RX 350 F-Sport in Atomic Silver exterior with Rioja Red leather interior.

Direct foreign used from the United States with clean title and zero duty issues. This particular unit comes with the full executive package — Mark Levinson 15-speaker premium audio, 360-degree surround camera system, panoramic power moonroof, adaptive cruise control, and driver attention monitor. Comprehensive pre-shipment inspection report available. All papers intact.`,
    price: 48500000,
    priceOnRequest: false,
    location: { city: 'Victoria Island', state: 'Lagos' },
    status: 'available',
    make: 'Lexus',
    model: 'RX 350 F-Sport',
    year: 2021,
    mileage: 38400,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Atomic Silver',
    features: [
      { label: 'Panoramic Moonroof', icon: 'sunroof' },
      { label: '360° Surround Camera', icon: 'cameras' },
      { label: 'Mark Levinson Audio', icon: 'audio' },
      { label: 'Adaptive Cruise Control', icon: 'cruise' },
      { label: 'Ventilated Front Seats', icon: 'seats' },
      { label: 'Head-Up Display', icon: 'hud' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348012345678' },
      { type: 'phone', label: 'Call Direct', value: '+2348012345678' },
      { type: 'email', label: 'Send Email Inquiry', value: 'sales@tradesqr.com' },
    ],
  },

  {
    _id: 'car-2',
    _type: 'listing',
    _createdAt: '2026-08-14T14:30:00Z',
    title: '2022 Mercedes-Benz GLE 450 4MATIC AMG Line',
    slug: { current: '2022-mercedes-benz-gle-450' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-2', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [
      { _type: 'image', asset: { _ref: 'img-c2-1', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80' },
    ],
    description: `Foreign used 2022 Mercedes-Benz GLE 450 with 3.0L Turbo Inline-6 EQ Boost mild-hybrid powertrain delivering 362hp.

AMG Line exterior/interior package, Burmester 3D surround audio, 64-color ambient lighting, MBUX dual 12.3-inch infotainment cluster, Airmatic air suspension, Distronic Plus radar cruise control, and 360° camera system. Duty fully paid.`,
    price: 82000000,
    priceOnRequest: false,
    location: { city: 'Maitama', state: 'Abuja' },
    status: 'available',
    make: 'Mercedes-Benz',
    model: 'GLE 450 AMG Line',
    year: 2022,
    mileage: 24500,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    condition: 'Foreign Used',
    color: 'Obsidian Black Metallic',
    features: [
      { label: 'Burmester 3D Surround Audio', icon: 'audio' },
      { label: '64-Color Ambient Lighting', icon: 'ambient' },
      { label: 'Airmatic Air Suspension', icon: 'suspension' },
      { label: 'Panoramic Sliding Roof', icon: 'sunroof' },
      { label: '360° Camera System', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348098765432' },
      { type: 'phone', label: 'Call Broker', value: '+2348098765432' },
    ],
  },

  {
    _id: 'car-3',
    _type: 'listing',
    _createdAt: '2026-08-13T09:00:00Z',
    title: '2020 Toyota Land Cruiser V8 (GXR, Locally Used)',
    slug: { current: '2020-toyota-land-cruiser-v8-gxr' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-3', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `2020 Toyota Land Cruiser V8 GXR in perfect running order. Single corporate owner from new, fully serviced at certified Toyota dealer with complete logbook history.

No accident history, pristine beige leather interior, cool box, rear entertainment screens, and 4-zone climate control. Available for direct physical inspection in Ikoyi.`,
    price: 95000000,
    priceOnRequest: false,
    location: { city: 'Ikoyi', state: 'Lagos' },
    status: 'available',
    make: 'Toyota',
    model: 'Land Cruiser V8 GXR',
    year: 2020,
    mileage: 52000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Pearl White',
    features: [
      { label: 'Multi-Terrain Select', icon: 'suspension' },
      { label: 'Crawl Control', icon: 'cruise' },
      { label: 'JBL Premium Audio', icon: 'audio' },
      { label: 'Cool Box Console', icon: 'ambient' },
      { label: 'Rear Camera System', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055667788' },
      { type: 'phone', label: 'Call Direct', value: '+2348055667788' },
    ],
  },

  {
    _id: 'car-4',
    _type: 'listing',
    _createdAt: '2026-08-12T07:00:00Z',
    title: '2023 BMW X5 xDrive40i M-Sport Package',
    slug: { current: '2023-bmw-x5-xdrive40i-msport' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-4', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Brand new 2023 BMW X5 xDrive40i with M-Sport exterior package, Vernasca Cognac leather, Harman Kardon surround audio, and BMW Laser Headlights. Zero mileage. Direct factory import with warranty.`,
    price: 135000000,
    priceOnRequest: false,
    location: { city: 'Lekki', state: 'Lagos' },
    status: 'available',
    make: 'BMW',
    model: 'X5 xDrive40i M-Sport',
    year: 2023,
    mileage: 120,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Brand New',
    color: 'Phytonic Blue',
    features: [
      { label: 'Harman Kardon Audio', icon: 'audio' },
      { label: 'Panoramic Glass Roof', icon: 'sunroof' },
      { label: 'BMW Laser Headlights', icon: 'hud' },
      { label: 'Adaptive Cruise Control', icon: 'cruise' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348044556677' },
      { type: 'phone', label: 'Call Dealer', value: '+2348044556677' },
    ],
  },

  {
    _id: 'car-5',
    _type: 'listing',
    _createdAt: '2026-08-11T12:00:00Z',
    title: '2017 Toyota Corolla LE (Foreign Used, Super Clean)',
    slug: { current: '2017-toyota-corolla-le' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-5', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Very clean 2017 Toyota Corolla LE, direct USA import. Fuel-efficient 1.8L 4-cylinder engine, reverse camera, lane departure alert, pre-collision assist, and cold AC. Ready for immediate daily driving with zero repairs needed.`,
    price: 8800000,
    priceOnRequest: false,
    location: { city: 'Ikeja', state: 'Lagos' },
    status: 'available',
    make: 'Toyota',
    model: 'Corolla LE',
    year: 2017,
    mileage: 78000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Classic Silver',
    features: [
      { label: 'Reverse Camera', icon: 'cameras' },
      { label: 'Lane Departure Alert', icon: 'cruise' },
      { label: 'Bluetooth Audio', icon: 'audio' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011223344' },
      { type: 'phone', label: 'Call Direct', value: '+2348011223344' },
    ],
  },

  {
    _id: 'car-6',
    _type: 'listing',
    _createdAt: '2026-08-10T16:00:00Z',
    title: '2016 Honda Accord EX-L V6 (Locally Used)',
    slug: { current: '2016-honda-accord-exl-v6' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-6', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Well-maintained 2016 Honda Accord EX-L V6. Engine and transmission in top shape, leather interior, sunroof, and dual-zone climate. Great budget daily car.`,
    price: 5400000,
    priceOnRequest: false,
    location: { city: 'Surulere', state: 'Lagos' },
    status: 'available',
    make: 'Honda',
    model: 'Accord EX-L',
    year: 2016,
    mileage: 114000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Modern Steel Metallic',
    features: [
      { label: 'Sunroof', icon: 'sunroof' },
      { label: 'Leather Seats', icon: 'seats' },
      { label: 'Right-turn LaneWatch Camera', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022334455' },
      { type: 'phone', label: 'Call Owner', value: '+2348022334455' },
    ],
  },

  {
    _id: 'car-7',
    _type: 'listing',
    _createdAt: '2026-08-09T11:00:00Z',
    title: '2019 Toyota Camry SE (Foreign Used)',
    slug: { current: '2019-toyota-camry-se' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-7', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Sporty 2019 Toyota Camry SE in Celestial Silver with black SofTex sport seats, 18-inch dual-spoke alloy wheels, paddle shifters, Entune touchscreen, and dual exhaust tips. Duty fully cleared.`,
    price: 14500000,
    priceOnRequest: false,
    location: { city: 'Wuse 2', state: 'Abuja' },
    status: 'available',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2019,
    mileage: 49000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Celestial Silver',
    features: [
      { label: 'Sport Alloy Wheels', icon: 'suspension' },
      { label: 'Paddle Shifters', icon: 'settings' },
      { label: 'Reverse Camera', icon: 'cameras' },
      { label: 'Adaptive Radar Cruise', icon: 'cruise' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033445566' },
      { type: 'phone', label: 'Call Direct', value: '+2348033445566' },
    ],
  },

  {
    _id: 'car-8',
    _type: 'listing',
    _createdAt: '2026-08-08T15:00:00Z',
    title: '2022 Range Rover Autobiography LWB (P530 V8)',
    slug: { current: '2022-range-rover-autobiography-lwb' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-8', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1541348263662-e0c86437fe1b?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `The pinnacle of luxury SUVs: 2022 New-shape Range Rover Autobiography Long Wheelbase (LWB) with 4.4L Twin-Turbo V8 (523hp). Executive class rear seating, Meridian Signature Sound (35 speakers), soft-close doors, air suspension, rear-wheel steering, and head-up display. Complete duty documents verified.`,
    price: 165000000,
    priceOnRequest: false,
    location: { city: 'Maitama', state: 'Abuja' },
    status: 'available',
    make: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2022,
    mileage: 16800,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Santorini Black',
    features: [
      { label: 'Executive Rear Seating', icon: 'seats' },
      { label: 'Meridian 35-Speaker Audio', icon: 'audio' },
      { label: 'Rear-Wheel Steering', icon: 'suspension' },
      { label: 'Panoramic Glass Roof', icon: 'sunroof' },
      { label: '360° 3D Camera System', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077889900' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348077889900' },
    ],
  },

  {
    _id: 'car-9',
    _type: 'listing',
    _createdAt: '2026-08-07T09:30:00Z',
    title: '2018 Ford Explorer Limited 4WD (Foreign Used)',
    slug: { current: '2018-ford-explorer-limited' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-9', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `3-row 7-seater SUV with Intelligent 4WD. Sony premium 12-speaker audio system, twin-panel moonroof, power folding 3rd-row seats, hands-free power tailgate, and front/rear cameras. Ideal family vehicle.`,
    price: 17200000,
    priceOnRequest: false,
    location: { city: 'GRA Phase 2', state: 'Port Harcourt' },
    status: 'available',
    make: 'Ford',
    model: 'Explorer Limited',
    year: 2018,
    mileage: 62000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Magnetic Metallic',
    features: [
      { label: '7-Passenger Seating', icon: 'seats' },
      { label: 'Twin-Panel Moonroof', icon: 'sunroof' },
      { label: 'Sony Premium Sound', icon: 'audio' },
      { label: 'Intelligent 4WD', icon: 'suspension' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088990011' },
      { type: 'phone', label: 'Call Direct', value: '+2348088990011' },
    ],
  },

  {
    _id: 'car-10',
    _type: 'listing',
    _createdAt: '2026-08-06T14:15:00Z',
    title: '2020 Hyundai Tucson Limited AWD (Locally Used)',
    slug: { current: '2020-hyundai-tucson-limited' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-10', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Extremely neat locally used Tucson Limited AWD. Leather seats, panoramic sunroof, infinity premium sound, Apple CarPlay, and wireless phone charging. First body, no repaint.`,
    price: 12800000,
    priceOnRequest: false,
    location: { city: 'Bodija', state: 'Ibadan' },
    status: 'available',
    make: 'Hyundai',
    model: 'Tucson Limited',
    year: 2020,
    mileage: 47000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Dusk Blue',
    features: [
      { label: 'Panoramic Sunroof', icon: 'sunroof' },
      { label: 'Apple CarPlay / Android Auto', icon: 'android-auto' },
      { label: 'Infinity Sound System', icon: 'audio' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011992288' },
      { type: 'phone', label: 'Call Direct', value: '+2348011992288' },
    ],
  },

  {
    _id: 'car-11',
    _type: 'listing',
    _createdAt: '2026-08-05T10:45:00Z',
    title: '2021 Mercedes-Benz C300 4MATIC AMG Line',
    slug: { current: '2021-mercedes-benz-c300-4matic' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-11', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Foreign used 2021 C300 4MATIC AMG package. Night package styling with blacked-out trims, Burmester sound, panoramic sunroof, ambient lighting, digital cockpit, and blind spot assist. All papers cleared.`,
    price: 38000000,
    priceOnRequest: false,
    location: { city: 'Lekki Phase 1', state: 'Lagos' },
    status: 'available',
    make: 'Mercedes-Benz',
    model: 'C300 AMG Line',
    year: 2021,
    mileage: 32000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Polar White',
    features: [
      { label: 'AMG Styling Package', icon: 'suspension' },
      { label: 'Burmester Surround Sound', icon: 'audio' },
      { label: 'Ambient Lighting', icon: 'ambient' },
      { label: 'Panoramic Sunroof', icon: 'sunroof' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348066554433' },
      { type: 'phone', label: 'Call Direct', value: '+2348066554433' },
    ],
  },

  {
    _id: 'car-12',
    _type: 'listing',
    _createdAt: '2026-08-04T16:20:00Z',
    title: '2015 Toyota RAV4 XLE AWD (Locally Used)',
    slug: { current: '2015-toyota-rav4-xle' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-12', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Reliable compact crossover with all-wheel drive, fabric interior in great condition, moonroof, dual climate, and factory reverse camera. Fully registered with genuine papers.`,
    price: 7800000,
    priceOnRequest: false,
    location: { city: 'Independence Layout', state: 'Enugu' },
    status: 'available',
    make: 'Toyota',
    model: 'RAV4 XLE',
    year: 2015,
    mileage: 95000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Magnetic Gray',
    features: [
      { label: 'Power Moonroof', icon: 'sunroof' },
      { label: 'All-Wheel Drive', icon: 'suspension' },
      { label: 'Backup Camera', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348044332211' },
      { type: 'phone', label: 'Call Seller', value: '+2348044332211' },
    ],
  },

  {
    _id: 'car-13',
    _type: 'listing',
    _createdAt: '2026-08-03T11:00:00Z',
    title: '2023 Toyota Hilux Adventure 2.8L Diesel 4x4',
    slug: { current: '2023-toyota-hilux-adventure-diesel' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-13', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Brand new 2023 Toyota Hilux Adventure Double Cabin. Powerful 2.8L Turbo Diesel engine paired with 6-speed automatic, JBL audio, 360 camera, leather seats, and rear differential lock. Built for Nigerian terrain.`,
    price: 62000000,
    priceOnRequest: false,
    location: { city: 'Central Business District', state: 'Abuja' },
    status: 'available',
    make: 'Toyota',
    model: 'Hilux Adventure',
    year: 2023,
    mileage: 50,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    condition: 'Brand New',
    color: 'Emotional Red',
    features: [
      { label: 'Heavy Duty 4x4 with Rear Lock', icon: 'suspension' },
      { label: 'JBL 9-Speaker Audio', icon: 'audio' },
      { label: '360° Camera System', icon: 'cameras' },
      { label: 'Leather Upholstery', icon: 'seats' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099881122' },
      { type: 'phone', label: 'Call Direct', value: '+2348099881122' },
    ],
  },

  {
    _id: 'car-14',
    _type: 'listing',
    _createdAt: '2026-08-02T13:30:00Z',
    title: '2020 Lexus ES 350 Ultra Luxury (Foreign Used)',
    slug: { current: '2020-lexus-es-350-ultra-luxury' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-14', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Whisper-quiet executive sedan: 2020 Lexus ES 350 Ultra Luxury. Semi-aniline leather seats, panoramic glass roof, 12.3-inch navigation screen, power rear sunshade, head-up display, and hands-free power trunk. Verified clean title.`,
    price: 33500000,
    priceOnRequest: false,
    location: { city: 'Gwarinpa', state: 'Abuja' },
    status: 'available',
    make: 'Lexus',
    model: 'ES 350 Ultra Luxury',
    year: 2020,
    mileage: 41000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Eminent White Pearl',
    features: [
      { label: 'Panoramic Glass Roof', icon: 'sunroof' },
      { label: 'Mark Levinson Audio', icon: 'audio' },
      { label: 'Semi-Aniline Leather Seats', icon: 'seats' },
      { label: 'Head-Up Display', icon: 'hud' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088776655' },
      { type: 'phone', label: 'Call Dealer', value: '+2348088776655' },
    ],
  },

  {
    _id: 'car-15',
    _type: 'listing',
    _createdAt: '2026-08-01T08:15:00Z',
    title: '2018 Mazda CX-5 Grand Touring AWD (Foreign Used)',
    slug: { current: '2018-mazda-cx-5-grand-touring' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-15', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Premium compact crossover in Soul Red Crystal Metallic. Bose 10-speaker sound system, head-up display, power moonroof, radar cruise control, and all-wheel drive.`,
    price: 13200000,
    priceOnRequest: false,
    location: { city: 'Jericho', state: 'Ibadan' },
    status: 'available',
    make: 'Mazda',
    model: 'CX-5 Grand Touring',
    year: 2018,
    mileage: 55000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Soul Red Crystal',
    features: [
      { label: 'Bose Centerpoint Sound', icon: 'audio' },
      { label: 'Head-Up Active Display', icon: 'hud' },
      { label: 'All-Wheel Drive', icon: 'suspension' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077665544' },
      { type: 'phone', label: 'Call Direct', value: '+2348077665544' },
    ],
  },

  {
    _id: 'car-16',
    _type: 'listing',
    _createdAt: '2026-07-30T15:40:00Z',
    title: '2019 Kia Sportage EX AWD (Locally Used)',
    slug: { current: '2019-kia-sportage-ex-awd' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-16', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Clean single-user locally used 2019 Sportage EX. Leather interior, panoramic sunroof, Apple CarPlay, blind spot detection, and fuel-efficient 2.4L engine.`,
    price: 9600000,
    priceOnRequest: false,
    location: { city: 'Peter Odili', state: 'Port Harcourt' },
    status: 'available',
    make: 'Kia',
    model: 'Sportage EX',
    year: 2019,
    mileage: 68000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Hyper Red',
    features: [
      { label: 'Panoramic Roof', icon: 'sunroof' },
      { label: 'Apple CarPlay', icon: 'android-auto' },
      { label: 'Rear Cross-Traffic Alert', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033221100' },
      { type: 'phone', label: 'Call Direct', value: '+2348033221100' },
    ],
  },

  {
    _id: 'car-17',
    _type: 'listing',
    _createdAt: '2026-07-28T11:20:00Z',
    title: '2021 Land Rover Defender 110 X-Dynamic SE',
    slug: { current: '2021-land-rover-defender-110' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-17', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1541348263662-e0c86437fe1b?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Foreign used Defender 110 with 3.0L i6 Turbocharged engine (395hp). Air suspension with adaptive dynamics, Meridian audio, 3D surround camera with Wade Sensing, panoramic roof, and black exterior package. Unmatched presence.`,
    price: 115000000,
    priceOnRequest: false,
    location: { city: 'Victoria Island', state: 'Lagos' },
    status: 'available',
    make: 'Land Rover',
    model: 'Defender 110 X-Dynamic',
    year: 2021,
    mileage: 28000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Carpathian Grey',
    features: [
      { label: 'Electronic Air Suspension', icon: 'suspension' },
      { label: '3D Surround Camera + Wade Sense', icon: 'cameras' },
      { label: 'Meridian Sound System', icon: 'audio' },
      { label: 'Panoramic Roof', icon: 'sunroof' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348066778899' },
      { type: 'phone', label: 'Call Direct', value: '+2348066778899' },
    ],
  },

  {
    _id: 'car-18',
    _type: 'listing',
    _createdAt: '2026-07-25T14:10:00Z',
    title: '2016 Toyota Highlander XLE AWD (Foreign Used)',
    slug: { current: '2016-toyota-highlander-xle' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-18', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Dependable 3.5L V6 3-row midsize SUV. Leather seats, sunroof, power liftgate, navigation, 8-inch touchscreen, and all-wheel drive. Great condition throughout.`,
    price: 16800000,
    priceOnRequest: false,
    location: { city: 'Nassarawa GRA', state: 'Kano' },
    status: 'available',
    make: 'Toyota',
    model: 'Highlander XLE',
    year: 2016,
    mileage: 72000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Midnight Black',
    features: [
      { label: '3-Row Seating', icon: 'seats' },
      { label: 'Power Moonroof', icon: 'sunroof' },
      { label: 'All-Wheel Drive', icon: 'suspension' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055443322' },
      { type: 'phone', label: 'Call Direct', value: '+2348055443322' },
    ],
  },

  {
    _id: 'car-19',
    _type: 'listing',
    _createdAt: '2026-07-22T09:00:00Z',
    title: '2022 BMW 530i M-Sport Edition (Foreign Used)',
    slug: { current: '2022-bmw-530i-msport' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-19', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Foreign used 2022 BMW 530i executive sedan with full M-Sport package, Dakota Cognac leather, Harman Kardon audio, BMW Live Cockpit Professional, and 19-inch M-wheels.`,
    price: 46000000,
    priceOnRequest: false,
    location: { city: 'Guzape', state: 'Abuja' },
    status: 'available',
    make: 'BMW',
    model: '530i M-Sport',
    year: 2022,
    mileage: 21000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Bernina Grey Amber Effect',
    features: [
      { label: 'M-Sport Aerodynamics', icon: 'suspension' },
      { label: 'Harman Kardon Surround', icon: 'audio' },
      { label: 'Ambient Interior Lighting', icon: 'ambient' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099001122' },
      { type: 'phone', label: 'Call Direct', value: '+2348099001122' },
    ],
  },

  {
    _id: 'car-20',
    _type: 'listing',
    _createdAt: '2026-07-20T17:00:00Z',
    title: '2017 Honda Civic Touring Turbo (Locally Used)',
    slug: { current: '2017-honda-civic-touring' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-20', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `High-trim Civic Touring with 1.5L Turbo engine. Premium 450W sound system with subwoofer, heated leather seats, LED headlights, Apple CarPlay, and navigation. Very fuel-efficient.`,
    price: 6900000,
    priceOnRequest: false,
    location: { city: 'Oluyole', state: 'Ibadan' },
    status: 'available',
    make: 'Honda',
    model: 'Civic Touring',
    year: 2017,
    mileage: 82000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Cosmic Blue Metallic',
    features: [
      { label: '450W Premium Audio', icon: 'audio' },
      { label: 'LED Headlights', icon: 'hud' },
      { label: 'Sunroof', icon: 'sunroof' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022113344' },
      { type: 'phone', label: 'Call Direct', value: '+2348022113344' },
    ],
  },

  {
    _id: 'car-21',
    _type: 'listing',
    _createdAt: '2026-07-18T12:00:00Z',
    title: '2020 Mercedes-Benz G63 AMG 4.0L Bi-Turbo',
    slug: { current: '2020-mercedes-benz-g63-amg' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-21', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Handcrafted 4.0L V8 Bi-Turbo (577hp) G-Wagon in Designo Night Black Magno with G Manufaktur Red/Black leather interior. AMG switchable performance exhaust, carbon fiber interior trim, Burmester sound, 22-inch forged cross-spoke wheels, and 3 locking differentials.`,
    price: 195000000,
    priceOnRequest: false,
    location: { city: 'Ikoyi', state: 'Lagos' },
    status: 'available',
    make: 'Mercedes-Benz',
    model: 'G63 AMG',
    year: 2020,
    mileage: 19500,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Night Black Magno',
    features: [
      { label: 'AMG Performance Exhaust', icon: 'settings' },
      { label: 'Burmester 3D Surround Audio', icon: 'audio' },
      { label: 'Carbon Fiber Trim', icon: 'suspension' },
      { label: '360° Surround Camera', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011993377' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348011993377' },
    ],
  },

  {
    _id: 'car-22',
    _type: 'listing',
    _createdAt: '2026-07-15T10:00:00Z',
    title: '2021 Ford F-150 Lariat 4x4 SuperCrew',
    slug: { current: '2021-ford-f150-lariat' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-22', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Foreign used 3.5L EcoBoost V6 pickup truck with 400hp and 500 lb-ft torque. 12-inch SYNC 4 screen, B&O Sound System by Bang & Olufsen, twin-panel moonroof, Pro Power Onboard generator, and FX4 Off-Road package.`,
    price: 42000000,
    priceOnRequest: false,
    location: { city: 'Old GRA', state: 'Port Harcourt' },
    status: 'available',
    make: 'Ford',
    model: 'F-150 Lariat',
    year: 2021,
    mileage: 36000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Agate Black',
    features: [
      { label: 'Bang & Olufsen Audio', icon: 'audio' },
      { label: 'Twin-Panel Moonroof', icon: 'sunroof' },
      { label: 'FX4 Off-Road Package', icon: 'suspension' },
      { label: 'Pro Power Onboard', icon: 'generator' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088112233' },
      { type: 'phone', label: 'Call Direct', value: '+2348088112233' },
    ],
  },

  {
    _id: 'car-23',
    _type: 'listing',
    _createdAt: '2026-07-12T16:00:00Z',
    title: '2018 Toyota Land Cruiser Prado TX-L Diesel (Locally Used)',
    slug: { current: '2018-toyota-prado-txl-diesel' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-23', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Robust 3.0L D-4D Turbo Diesel Prado with low fuel consumption and rugged reliability. 7-seater, coolbox, push-button start, leather interior, and side steps. Full registration documents.`,
    price: 45000000,
    priceOnRequest: false,
    location: { city: 'Asokoro', state: 'Abuja' },
    status: 'available',
    make: 'Toyota',
    model: 'Land Cruiser Prado TX-L',
    year: 2018,
    mileage: 74000,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    condition: 'Locally Used',
    color: 'Silver Metallic',
    features: [
      { label: '7-Passenger Seating', icon: 'seats' },
      { label: 'Cool Box Console', icon: 'ambient' },
      { label: '4WD with Low Range', icon: 'suspension' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348044998877' },
      { type: 'phone', label: 'Call Direct', value: '+2348044998877' },
    ],
  },

  {
    _id: 'car-24',
    _type: 'listing',
    _createdAt: '2026-07-10T11:30:00Z',
    title: '2023 Hyundai Santa Fe Calligraphy AWD',
    slug: { current: '2023-hyundai-santa-fe-calligraphy' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-24', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Brand new top-of-the-line Calligraphy trim. Quilted Nappa leather seats, Harman Kardon audio, surround view monitor, 2.5L Turbo engine with 281hp, head-up display, and remote smart parking assist.`,
    price: 54000000,
    priceOnRequest: false,
    location: { city: 'Ikeja GRA', state: 'Lagos' },
    status: 'available',
    make: 'Hyundai',
    model: 'Santa Fe Calligraphy',
    year: 2023,
    mileage: 250,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Brand New',
    color: 'Portofino Gray',
    features: [
      { label: 'Nappa Leather Upholstery', icon: 'seats' },
      { label: 'Harman Kardon Audio', icon: 'audio' },
      { label: 'Remote Smart Parking Assist', icon: 'cruise' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055112233' },
      { type: 'phone', label: 'Call Dealer', value: '+2348055112233' },
    ],
  },

  {
    _id: 'car-25',
    _type: 'listing',
    _createdAt: '2026-07-08T14:00:00Z',
    title: '2016 Lexus IS 250 F-Sport (Foreign Used)',
    slug: { current: '2016-lexus-is-250-fsport' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-25', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Sporty and agile compact luxury sedan with F-Sport digital instrument cluster, red sport leather seats, sunroof, and paddle shifters. Excellent condition.`,
    price: 11500000,
    priceOnRequest: false,
    location: { city: 'GRA', state: 'Enugu' },
    status: 'available',
    make: 'Lexus',
    model: 'IS 250 F-Sport',
    year: 2016,
    mileage: 69000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Ultra White',
    features: [
      { label: 'F-Sport Digital Cluster', icon: 'hud' },
      { label: 'Sport Seats', icon: 'seats' },
      { label: 'Sunroof', icon: 'sunroof' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033669988' },
      { type: 'phone', label: 'Call Direct', value: '+2348033669988' },
    ],
  },

  {
    _id: 'car-26',
    _type: 'listing',
    _createdAt: '2026-07-05T09:45:00Z',
    title: '2022 Toyota Sequoia TRD Pro 4WD (Hybrid i-FORCE MAX)',
    slug: { current: '2022-toyota-sequoia-trd-pro' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-26', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Full-size 3-row off-road flagship with 437hp twin-turbo hybrid V6 powertrain. FOX internal bypass shocks, 14-inch touchscreen, panoramic moonroof, JBL 14-speaker sound, and multi-terrain monitor.`,
    price: 98000000,
    priceOnRequest: false,
    location: { city: 'Jabi', state: 'Abuja' },
    status: 'available',
    make: 'Toyota',
    model: 'Sequoia TRD Pro',
    year: 2022,
    mileage: 22000,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    condition: 'Foreign Used',
    color: 'Solar Octane',
    features: [
      { label: 'FOX Off-Road Shocks', icon: 'suspension' },
      { label: '14-inch Infotainment Screen', icon: 'hud' },
      { label: 'JBL 14-Speaker Audio', icon: 'audio' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011229988' },
      { type: 'phone', label: 'Call Direct', value: '+2348011229988' },
    ],
  },

  {
    _id: 'car-27',
    _type: 'listing',
    _createdAt: '2026-07-02T16:15:00Z',
    title: '2019 Mazda 6 Signature 2.5T (Foreign Used)',
    slug: { current: '2019-mazda-6-signature' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-27', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Flagship Signature trim featuring genuine Japanese Sen wood accents, Nappa leather, 2.5L Turbo engine with 250hp, 360 camera, ventilated front seats, and Bose 11-speaker system.`,
    price: 12400000,
    priceOnRequest: false,
    location: { city: 'Yaba', state: 'Lagos' },
    status: 'available',
    make: 'Mazda',
    model: '6 Signature',
    year: 2019,
    mileage: 51000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Foreign Used',
    color: 'Machine Gray Metallic',
    features: [
      { label: 'Nappa Leather & Sen Wood', icon: 'seats' },
      { label: 'Bose 11-Speaker Audio', icon: 'audio' },
      { label: '360° View Monitor', icon: 'cameras' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077553311' },
      { type: 'phone', label: 'Call Direct', value: '+2348077553311' },
    ],
  },

  {
    _id: 'car-28',
    _type: 'listing',
    _createdAt: '2026-07-01T10:00:00Z',
    title: '2015 Toyota Yaris Sedan (Locally Used)',
    slug: { current: '2015-toyota-yaris-sedan' },
    category: 'cars',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-car-28', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Affordable and ultra-reliable 1.5L Toyota Yaris. Low running costs, ice-cold air conditioning, neat fabric interior, and smooth automatic transmission. Ideal city commuter.`,
    price: 4200000,
    priceOnRequest: false,
    location: { city: 'Alausa', state: 'Lagos' },
    status: 'available',
    make: 'Toyota',
    model: 'Yaris Sedan',
    year: 2015,
    mileage: 128000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    condition: 'Locally Used',
    color: 'Super White',
    features: [
      { label: 'Factory Air Conditioning', icon: 'ac' },
      { label: 'Power Windows', icon: 'settings' },
      { label: 'Central Locking', icon: 'security' },
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022998877' },
      { type: 'phone', label: 'Call Owner', value: '+2348022998877' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // REAL ESTATE (23 Listings: studios to mansions, sale/rent/lease)
  // ─────────────────────────────────────────────────────────────────────────
  {
    _id: 'house-1',
    _type: 'listing',
    _createdAt: '2026-08-13T09:15:00Z',
    title: 'Luxury 5-Bedroom Fully Detached Duplex + BQ & Swimming Pool',
    slug: { current: 'luxury-5-bedroom-detached-duplex-lekki' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-1', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [
      { _type: 'image', asset: { _ref: 'img-h1-1', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80' },
      { _type: 'image', asset: { _ref: 'img-h1-2', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80' },
    ],
    description: `Newly built contemporary 5-bedroom detached mansion situated within a secure, gated estate in Lekki Phase 1.

Each bedroom is fully en-suite with Italian Porcelain tiles, Italian chef kitchen with island, private cinema room, rooftop lounge with city views, infinity swimming pool, stamped concrete compound with parking for up to 6 vehicles, and an integrated Crestron home automation system.

Title is Governor's Consent — fully perfected and ready for immediate transfer.`,
    price: 380000000,
    priceOnRequest: false,
    location: { city: 'Lekki Phase 1', state: 'Lagos' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 5,
    sizeSqm: 650,
    listingPurpose: 'sale',
    features: [
      { label: 'Infinity Swimming Pool', icon: 'pool' },
      { label: 'Private Cinema Room', icon: 'cinema' },
      { label: 'Smart Home Automation', icon: 'smart-home' },
      { label: 'Rooftop Lounge', icon: 'rooftop' },
      { label: 'Italian Chef Kitchen', icon: 'kitchen' },
      { label: 'CCTV Surveillance', icon: 'cctv' },
      { label: 'Parking for 6 Vehicles', icon: 'parking' },
      { label: '24hr Power Supply', icon: 'generator' },
    ],
    documents: [
      "Governor's Consent",
      'Survey Plan',
      'Building Approval',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011223344' },
      { type: 'phone', label: 'Call Direct', value: '+2348011223344' },
    ],
  },

  {
    _id: 'house-2',
    _type: 'listing',
    _createdAt: '2026-08-12T16:45:00Z',
    title: '4-Bedroom Contemporary Terrace Duplex in Gated Estate',
    slug: { current: '4-bedroom-contemporary-terrace-ikoyi' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-2', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Prestigious 4-bedroom terrace duplex in Old Ikoyi with 24/7 dedicated power generation and manned security post. Features custom woodwork, all-ensuite bedrooms, balcony with greenery views, and high rental yield potential.`,
    price: 285000000,
    priceOnRequest: false,
    location: { city: 'Old Ikoyi', state: 'Lagos' },
    status: 'available',
    propertyType: 'Terrace',
    bedrooms: 4,
    sizeSqm: 380,
    listingPurpose: 'sale',
    features: [
      { label: '24/7 Power Generation', icon: 'generator' },
      { label: 'Manned Security Post', icon: 'security' },
      { label: 'Balcony with Views', icon: 'balcony' },
      { label: 'All Ensuite Rooms', icon: 'ensuite' },
    ],
    documents: [
      'C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022334455' },
      { type: 'phone', label: 'Call Direct', value: '+2348022334455' },
    ],
  },

  {
    _id: 'house-3',
    _type: 'listing',
    _createdAt: '2026-08-11T14:00:00Z',
    title: '4-Bedroom Semi-Detached Duplex with Smart Home, Guzape Abuja',
    slug: { current: '4-bedroom-semi-detached-guzape-abuja' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-3', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Modern 4-bedroom duplex with picturesque hilltop views in Guzape District, Abuja. Smart home automation controlling lights and AC, imported sanitary ware, and spacious private parking.`,
    price: 210000000,
    priceOnRequest: false,
    location: { city: 'Guzape', state: 'Abuja' },
    status: 'available',
    propertyType: 'Semi-Detached',
    bedrooms: 4,
    sizeSqm: 420,
    listingPurpose: 'sale',
    features: [
      { label: 'Smart Home Automation', icon: 'smart-home' },
      { label: 'CCTV Surveillance', icon: 'cctv' },
      { label: 'Hilltop Views', icon: 'view' },
      { label: 'Central Air Conditioning', icon: 'ac' },
    ],
    documents: [
      'R of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099887766' },
      { type: 'phone', label: 'Call Broker', value: '+2348099887766' },
    ],
  },

  {
    _id: 'house-4',
    _type: 'listing',
    _createdAt: '2026-08-09T10:00:00Z',
    title: 'Modern 2-Bedroom Serviced Apartment in Oniru Victoria Island',
    slug: { current: 'modern-2-bedroom-serviced-apartment-oniru' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-4', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Spacious serviced 2-bedroom apartment with 24/7 power, elevator, swimming pool, gym, and designated parking. Minutes away from VI and Lekki Phase 1. Yearly rental.`,
    price: 4500000,
    priceOnRequest: false,
    location: { city: 'Oniru', state: 'Lagos' },
    status: 'available',
    propertyType: 'Apartment',
    bedrooms: 2,
    sizeSqm: 140,
    listingPurpose: 'rent',
    features: [
      { label: '24/7 Dedicated Power', icon: 'generator' },
      { label: 'Communal Swimming Pool', icon: 'pool' },
      { label: 'Fitted Gym', icon: 'gym' },
      { label: 'Elevator', icon: 'elevator' },
    ],
    documents: [
      'Tenancy Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011994455' },
      { type: 'phone', label: 'Call Letting Agent', value: '+2348011994455' },
    ],
  },

  {
    _id: 'house-5',
    _type: 'listing',
    _createdAt: '2026-08-08T12:00:00Z',
    title: '3-Bedroom Luxury Waterfront Penthouse in Eko Atlantic',
    slug: { current: '3-bedroom-luxury-penthouse-eko-atlantic' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-5', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Ultra-modern penthouse tower offering floor-to-ceiling glass walls with direct Atlantic Ocean views. Features private plunge pool, Miele kitchen appliances, smart climate control, and 3 underground parking bays.`,
    price: 520000000,
    priceOnRequest: false,
    location: { city: 'Eko Atlantic City', state: 'Lagos' },
    status: 'available',
    propertyType: 'Penthouse',
    bedrooms: 3,
    sizeSqm: 480,
    listingPurpose: 'sale',
    features: [
      { label: 'Direct Ocean View', icon: 'waterfront' },
      { label: 'Private Plunge Pool', icon: 'pool' },
      { label: 'Smart Home Integration', icon: 'smart-home' },
      { label: '24hr Concierge', icon: 'security' },
    ],
    documents: [
      'Federal C of O',
      'Deed of Sublease',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077661122' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348077661122' },
    ],
  },

  {
    _id: 'house-6',
    _type: 'listing',
    _createdAt: '2026-08-06T15:00:00Z',
    title: '6-Bedroom Ambassadorial Mansion on 1,800 sqm Grounds, Maitama',
    slug: { current: '6-bedroom-ambassadorial-mansion-maitama' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-6', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Palatial residence suitable for high-ranking diplomat or corporate executive. Features grand foyer, Olympic-sized swimming pool, 2-bedroom guest chalet, 4-room BQ, landscaped gardens, and parking for 15+ vehicles.`,
    price: 950000000,
    priceOnRequest: false,
    location: { city: 'Maitama', state: 'Abuja' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 6,
    sizeSqm: 1800,
    listingPurpose: 'sale',
    features: [
      { label: 'Olympic Swimming Pool', icon: 'pool' },
      { label: 'Guest Chalet & 4 BQs', icon: 'ensuite' },
      { label: 'Parking for 15 Vehicles', icon: 'parking' },
      { label: 'Bulletproof Main Doors', icon: 'security' },
    ],
    documents: [
      'C of O',
      'FCDA Building Approval',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055441100' },
      { type: 'phone', label: 'Call Direct', value: '+2348055441100' },
    ],
  },

  {
    _id: 'house-7',
    _type: 'listing',
    _createdAt: '2026-08-05T09:00:00Z',
    title: '3-Bedroom Luxury Serviced Flat with Elevator, Wuse 2 Abuja',
    slug: { current: '3-bedroom-serviced-flat-wuse-2' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-7', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Executive rental in the heart of Wuse 2. Fully furnished options available, central AC, continuous power generation, gym, and 24/7 security. Ready for immediate occupancy.`,
    price: 8000000,
    priceOnRequest: false,
    location: { city: 'Wuse 2', state: 'Abuja' },
    status: 'available',
    propertyType: 'Apartment',
    bedrooms: 3,
    sizeSqm: 210,
    listingPurpose: 'rent',
    features: [
      { label: '24hr Uninterrupted Power', icon: 'generator' },
      { label: 'High-speed Elevator', icon: 'elevator' },
      { label: 'Fitted Gymnasium', icon: 'gym' },
    ],
    documents: [
      'Tenancy Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033224488' },
      { type: 'phone', label: 'Call Direct', value: '+2348033224488' },
    ],
  },

  {
    _id: 'house-8',
    _type: 'listing',
    _createdAt: '2026-08-03T14:30:00Z',
    title: '4-Bedroom Fully Detached Duplex with BQ, Chevron Lekki',
    slug: { current: '4-bedroom-detached-chevron-lekki' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-8', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Contemporary family home with fully fitted kitchen, stamped concrete compound, automated gate, all en-suite bedrooms, and spacious family lounge on the upper floor. Governor's consent.`,
    price: 135000000,
    priceOnRequest: false,
    location: { city: 'Chevron Axis', state: 'Lagos' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 4,
    sizeSqm: 350,
    listingPurpose: 'sale',
    features: [
      { label: 'Fitted Kitchen with Heat Extractor', icon: 'kitchen' },
      { label: 'Automated Gate', icon: 'smart-home' },
      { label: 'All Rooms En-suite', icon: 'ensuite' },
    ],
    documents: [
      "Governor's Consent",
      'Building Approval',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011776655' },
      { type: 'phone', label: 'Call Agent', value: '+2348011776655' },
    ],
  },

  {
    _id: 'house-9',
    _type: 'listing',
    _createdAt: '2026-08-01T11:00:00Z',
    title: 'Open-Plan Commercial Office Floor (650 sqm), Victoria Island',
    slug: { current: 'commercial-office-floor-victoria-island' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-9', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Grade-A commercial office space in corporate Victoria Island. Raised flooring, central HVAC, 3 passenger elevators, 100% backup power redundancy, and designated underground parking bays.`,
    price: 28000000,
    priceOnRequest: false,
    location: { city: 'Victoria Island', state: 'Lagos' },
    status: 'available',
    propertyType: 'Commercial',
    bedrooms: 0,
    sizeSqm: 650,
    listingPurpose: 'lease',
    features: [
      { label: 'Grade-A Commercial Infrastructure', icon: 'infrastructure' },
      { label: 'Redundant Power Supply', icon: 'generator' },
      { label: 'Underground Parking', icon: 'parking' },
      { label: 'Central HVAC System', icon: 'ac' },
    ],
    documents: [
      'Commercial Lease Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099884433' },
      { type: 'phone', label: 'Call Commercial Desk', value: '+2348099884433' },
    ],
  },

  {
    _id: 'house-10',
    _type: 'listing',
    _createdAt: '2026-07-29T16:00:00Z',
    title: 'Furnished 1-Bedroom Studio Apartment in Tech Hub Yaba',
    slug: { current: 'furnished-studio-apartment-yaba' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-10', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Compact, modern studio flat with kitchenette, high-speed fiber internet connection, security, and power backup. Perfect for single professionals and remote workers.`,
    price: 2200000,
    priceOnRequest: false,
    location: { city: 'Yaba', state: 'Lagos' },
    status: 'available',
    propertyType: 'Studio',
    bedrooms: 1,
    sizeSqm: 55,
    listingPurpose: 'rent',
    features: [
      { label: 'High-Speed Fiber Internet', icon: 'wifi' },
      { label: 'Power Backup', icon: 'generator' },
      { label: 'Fitted Kitchenette', icon: 'kitchen' },
    ],
    documents: [
      'Tenancy Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348066551122' },
      { type: 'phone', label: 'Call Agent', value: '+2348066551122' },
    ],
  },

  {
    _id: 'house-11',
    _type: 'listing',
    _createdAt: '2026-07-27T10:30:00Z',
    title: '5-Bedroom Fully Automated Smart Villa, Asokoro Abuja',
    slug: { current: '5-bedroom-smart-villa-asokoro' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-11', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Architectural masterpiece in Asokoro featuring private elevator, cinema hall, indoor heated pool, solar hybrid inverter system, and lush landscaped garden. C of O on ground.`,
    price: 420000000,
    priceOnRequest: false,
    location: { city: 'Asokoro', state: 'Abuja' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 5,
    sizeSqm: 800,
    listingPurpose: 'sale',
    features: [
      { label: 'Private Elevator', icon: 'elevator' },
      { label: 'Indoor Heated Pool', icon: 'pool' },
      { label: 'Smart Home Controls', icon: 'smart-home' },
      { label: 'Solar Hybrid Power System', icon: 'generator' },
    ],
    documents: [
      'C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088223344' },
      { type: 'phone', label: 'Call Direct', value: '+2348088223344' },
    ],
  },

  {
    _id: 'house-12',
    _type: 'listing',
    _createdAt: '2026-07-25T13:00:00Z',
    title: '3-Bedroom Terrace Duplex in Gated Estate, Bodija Ibadan',
    slug: { current: '3-bedroom-terrace-bodija-ibadan' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-12', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Newly finished 3-bedroom terrace duplex in a serene, gated community in Bodija. Spacious living room, modern kitchen, dedicated parking space, and perimeter electric fencing.`,
    price: 68000000,
    priceOnRequest: false,
    location: { city: 'Bodija', state: 'Ibadan' },
    status: 'available',
    propertyType: 'Terrace',
    bedrooms: 3,
    sizeSqm: 260,
    listingPurpose: 'sale',
    features: [
      { label: 'Gated Security Estate', icon: 'security' },
      { label: 'Modern Kitchen Cabinets', icon: 'kitchen' },
      { label: 'Perimeter Electric Fence', icon: 'fence' },
    ],
    documents: [
      'Red Copy Survey',
      'Deed of Assignment',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348044778899' },
      { type: 'phone', label: 'Call Owner', value: '+2348044778899' },
    ],
  },

  {
    _id: 'house-13',
    _type: 'listing',
    _createdAt: '2026-07-22T08:00:00Z',
    title: '4-Bedroom Waterfront Duplex with Private Boat Jetty, Banana Island',
    slug: { current: 'waterfront-duplex-banana-island' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-13', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Ultra-luxury waterfront property on Banana Island. Direct lagoon access with private boat jetty, infinity pool overlooking the water, Italian marble finishes, and 2-room staff quarters.`,
    price: 750000000,
    priceOnRequest: false,
    location: { city: 'Banana Island, Ikoyi', state: 'Lagos' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 4,
    sizeSqm: 720,
    listingPurpose: 'sale',
    features: [
      { label: 'Private Boat Jetty', icon: 'waterfront' },
      { label: 'Lagoon-facing Infinity Pool', icon: 'pool' },
      { label: 'Italian Marble Flooring', icon: 'woodwork' },
      { label: '24hr Security Patrol', icon: 'security' },
    ],
    documents: [
      'Federal C of O',
      "Governor's Consent",
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011883344' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348011883344' },
    ],
  },

  {
    _id: 'house-14',
    _type: 'listing',
    _createdAt: '2026-07-20T14:45:00Z',
    title: 'Executive 4-Bedroom Detached Bungalow on 2 Plots, GRA Port Harcourt',
    slug: { current: '4-bedroom-bungalow-gra-port-harcourt' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-14', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Spacious, solidly built detached bungalow on two full plots in quiet GRA Phase 2. Large green lawn, generator house, 2-room staff quarters, borehole water treatment plant, and massive parking space.`,
    price: 85000000,
    priceOnRequest: false,
    location: { city: 'GRA Phase 2', state: 'Port Harcourt' },
    status: 'available',
    propertyType: 'Bungalow',
    bedrooms: 4,
    sizeSqm: 1200,
    listingPurpose: 'sale',
    features: [
      { label: 'Massive Green Compound', icon: 'dry-land' },
      { label: 'Water Treatment Plant', icon: 'infrastructure' },
      { label: 'Security Gatehouse', icon: 'security' },
    ],
    documents: [
      'Rivers State C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099112233' },
      { type: 'phone', label: 'Call Direct', value: '+2348099112233' },
    ],
  },

  {
    _id: 'house-15',
    _type: 'listing',
    _createdAt: '2026-07-17T11:20:00Z',
    title: '2-Bedroom Shortlet-Ready Apartment in Ikate Elegushi, Lekki',
    slug: { current: '2-bedroom-apartment-ikate-lekki' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-15', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `High-yield investment apartment in Ikate. Guaranteed shortlet cashflow with average monthly revenue of ₦1.8M+. Fully fitted kitchen, smart door lock, swimming pool, and dedicated security.`,
    price: 55000000,
    priceOnRequest: false,
    location: { city: 'Ikate Elegushi', state: 'Lagos' },
    status: 'available',
    propertyType: 'Apartment',
    bedrooms: 2,
    sizeSqm: 125,
    listingPurpose: 'sale',
    features: [
      { label: 'High Shortlet Yield', icon: 'smart-home' },
      { label: 'Swimming Pool', icon: 'pool' },
      { label: 'Smart Keyless Entry', icon: 'security' },
    ],
    documents: [
      "Governor's Consent",
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077443322' },
      { type: 'phone', label: 'Call Investment Desk', value: '+2348077443322' },
    ],
  },

  {
    _id: 'house-16',
    _type: 'listing',
    _createdAt: '2026-07-14T09:30:00Z',
    title: '5-Bedroom Contemporary Mansion in Gated Estate, Independence Layout',
    slug: { current: '5-bedroom-mansion-independence-layout-enugu' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-16', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Newly constructed luxury mansion in Enugu's premier neighborhood. High ceilings, POP design, granite staircases, ensuite bedrooms, CCTV surveillance, and parking for 8 cars.`,
    price: 175000000,
    priceOnRequest: false,
    location: { city: 'Independence Layout', state: 'Enugu' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 5,
    sizeSqm: 680,
    listingPurpose: 'sale',
    features: [
      { label: 'Grand Foyer & High Ceilings', icon: 'rooftop' },
      { label: 'CCTV Perimeter Security', icon: 'cctv' },
      { label: 'Granite & Italian Tile Finishes', icon: 'woodwork' },
    ],
    documents: [
      'Enugu State C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055223311' },
      { type: 'phone', label: 'Call Direct', value: '+2348055223311' },
    ],
  },

  {
    _id: 'house-17',
    _type: 'listing',
    _createdAt: '2026-07-11T16:00:00Z',
    title: 'Retail Showroom on Ground Floor (320 sqm), Garki 2 Abuja',
    slug: { current: 'retail-showroom-garki-2-abuja' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-17', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `High-visibility commercial ground-floor space directly facing major arterial road. Glass facade, dedicated generator, spacious customer parking, and high footfall area.`,
    price: 14000000,
    priceOnRequest: false,
    location: { city: 'Garki 2', state: 'Abuja' },
    status: 'available',
    propertyType: 'Commercial',
    bedrooms: 0,
    sizeSqm: 320,
    listingPurpose: 'lease',
    features: [
      { label: 'High Footfall Main Road', icon: 'road' },
      { label: 'Full Glass Display Facade', icon: 'view' },
      { label: 'Customer Parking Lot', icon: 'parking' },
    ],
    documents: [
      'Commercial Lease Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033887766' },
      { type: 'phone', label: 'Call Commercial Agent', value: '+2348033887766' },
    ],
  },

  {
    _id: 'house-18',
    _type: 'listing',
    _createdAt: '2026-07-09T10:15:00Z',
    title: '3-Bedroom Semi-Detached Duplex in Magodo Phase 2, Lagos',
    slug: { current: '3-bedroom-semi-detached-magodo' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-18', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Family duplex in highly secure Magodo Phase 2 estate. Serene environment, treated water, prepaid meter, parking for 3 cars, and round-the-clock estate gate security. Yearly rent.`,
    price: 3800000,
    priceOnRequest: false,
    location: { city: 'Magodo Phase 2', state: 'Lagos' },
    status: 'available',
    propertyType: 'Semi-Detached',
    bedrooms: 3,
    sizeSqm: 220,
    listingPurpose: 'rent',
    features: [
      { label: 'Gated Estate with Access Control', icon: 'security' },
      { label: 'Borehole Water Treatment', icon: 'infrastructure' },
      { label: 'Prepaid Electricity Meter', icon: 'generator' },
    ],
    documents: [
      'Tenancy Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022884411' },
      { type: 'phone', label: 'Call Letting Desk', value: '+2348022884411' },
    ],
  },

  {
    _id: 'house-19',
    _type: 'listing',
    _createdAt: '2026-07-06T15:30:00Z',
    title: '4-Bedroom Semi-Detached Duplex with Swimming Pool, Katampe Abuja',
    slug: { current: '4-bedroom-semi-detached-katampe' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-19', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Elevated hilltop luxury duplex in Katampe Extension. Swimming pool, smart doorbells, modern fitted kitchen, ensuite rooms with walk-in closets, and panoramic city views.`,
    price: 160000000,
    priceOnRequest: false,
    location: { city: 'Katampe Extension', state: 'Abuja' },
    status: 'available',
    propertyType: 'Semi-Detached',
    bedrooms: 4,
    sizeSqm: 380,
    listingPurpose: 'sale',
    features: [
      { label: 'Private Swimming Pool', icon: 'pool' },
      { label: 'Walk-in Wardrobes', icon: 'ensuite' },
      { label: 'Panoramic City Views', icon: 'view' },
    ],
    documents: [
      'C of O',
      'Building Approval',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099332211' },
      { type: 'phone', label: 'Call Direct', value: '+2348099332211' },
    ],
  },

  {
    _id: 'house-20',
    _type: 'listing',
    _createdAt: '2026-07-04T12:00:00Z',
    title: 'Ultra-Modern 5-Bedroom Detached Duplex in Oluyole Estate, Ibadan',
    slug: { current: '5-bedroom-detached-oluyole-ibadan' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-20', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Brand new duplex in prime Oluyole Estate. Stamped concrete compound, high-grade security doors, solar inverter setup, pop ceilings, and master bedroom with jacuzzi.`,
    price: 110000000,
    priceOnRequest: false,
    location: { city: 'Oluyole Estate', state: 'Ibadan' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 5,
    sizeSqm: 500,
    listingPurpose: 'sale',
    features: [
      { label: 'Solar Inverter Backup', icon: 'generator' },
      { label: 'Master Bedroom Jacuzzi', icon: 'bathroom' },
      { label: 'Stamped Concrete Yard', icon: 'parking' },
    ],
    documents: [
      'C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077114455' },
      { type: 'phone', label: 'Call Owner', value: '+2348077114455' },
    ],
  },

  {
    _id: 'house-21',
    _type: 'listing',
    _createdAt: '2026-07-02T09:00:00Z',
    title: '1-Bedroom Serviced Mini Flat in Surulere, Lagos',
    slug: { current: '1-bedroom-serviced-mini-flat-surulere' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-21', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Neat and accessible 1-bedroom mini flat off Adeniran Ogunsanya. Prepaid meter, dedicated parking slot, gated street security, and easy commute to Lagos Island.`,
    price: 1800000,
    priceOnRequest: false,
    location: { city: 'Surulere', state: 'Lagos' },
    status: 'available',
    propertyType: 'Apartment',
    bedrooms: 1,
    sizeSqm: 65,
    listingPurpose: 'rent',
    features: [
      { label: 'Gated Street Security', icon: 'security' },
      { label: 'Prepaid Electric Meter', icon: 'generator' },
      { label: 'Dedicated Parking', icon: 'parking' },
    ],
    documents: [
      'Tenancy Agreement',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011335577' },
      { type: 'phone', label: 'Call Agent', value: '+2348011335577' },
    ],
  },

  {
    _id: 'house-22',
    _type: 'listing',
    _createdAt: '2026-06-30T14:20:00Z',
    title: '4-Bedroom Terrace Duplex on Peter Odili Road, Port Harcourt',
    slug: { current: '4-bedroom-terrace-peter-odili' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-22', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Executive 4-bedroom terrace duplex in a fully paved estate on Peter Odili corridor. 24/7 security, central water system, and modern fitted kitchen.`,
    price: 95000000,
    priceOnRequest: false,
    location: { city: 'Peter Odili', state: 'Port Harcourt' },
    status: 'available',
    propertyType: 'Terrace',
    bedrooms: 4,
    sizeSqm: 320,
    listingPurpose: 'sale',
    features: [
      { label: 'Central Water System', icon: 'infrastructure' },
      { label: '24/7 Manned Estate Security', icon: 'security' },
      { label: 'Paved Access Road', icon: 'road' },
    ],
    documents: [
      'Deed of Conveyance',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088442299' },
      { type: 'phone', label: 'Call Direct', value: '+2348088442299' },
    ],
  },

  {
    _id: 'house-23',
    _type: 'listing',
    _createdAt: '2026-06-28T11:00:00Z',
    title: 'Luxury 6-Bedroom Detached Mansion with Cinema & Lakefront, Jabi Abuja',
    slug: { current: '6-bedroom-lakefront-mansion-jabi' },
    category: 'realEstate',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-house-23', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Lakefront trophy asset in Jabi District. Features 12-seat private cinema, infinity pool over the lake, central sound, elevator across 3 floors, and 4-room BQ.`,
    price: 620000000,
    priceOnRequest: false,
    location: { city: 'Jabi Lakefront', state: 'Abuja' },
    status: 'available',
    propertyType: 'Detached',
    bedrooms: 6,
    sizeSqm: 1100,
    listingPurpose: 'sale',
    features: [
      { label: 'Lakefront Panoramic View', icon: 'waterfront' },
      { label: '12-Seat Cinema Room', icon: 'cinema' },
      { label: 'Private Elevator', icon: 'elevator' },
      { label: 'Infinity Pool', icon: 'pool' },
    ],
    documents: [
      'C of O',
      'FCDA Approved Building Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055889900' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348055889900' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LAND (17 Listings: plots to multi-hectare estates across Nigeria)
  // ─────────────────────────────────────────────────────────────────────────
  {
    _id: 'land-1',
    _type: 'listing',
    _createdAt: '2026-08-11T11:20:00Z',
    title: 'Prime 2,000 sqm Commercial Plot Facing Lekki-Epe Expressway',
    slug: { current: 'prime-commercial-plot-lekki-epe' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-1', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [
      { _type: 'image', asset: { _ref: 'img-l1-1', _type: 'reference' }, url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80' },
    ],
    description: `Strategic corner-piece dry commercial land directly on the Lekki-Epe Expressway corridor. Ideal for retail plaza, bank branch, corporate headquarters, hotel, or auto dealership showroom.

100% dry ground throughout the year with no flood risk. Fully perimeter-fenced with block walls, registered Certificate of Occupancy (C of O) in hand.`,
    price: 450000000,
    priceOnRequest: false,
    location: { city: 'Epe Corridor', state: 'Lagos' },
    status: 'available',
    plots: 3.3,
    landSizeSqm: 2000,
    landPurpose: 'sale',
    features: [
      { label: 'Fully Perimeter Fenced', icon: 'fence' },
      { label: '100% Dry Land', icon: 'dry-land' },
      { label: 'Expressway Frontage', icon: 'road' },
      { label: 'Corner Piece Plot', icon: 'corner' },
      { label: 'Electricity On Site', icon: 'electricity' },
    ],
    documents: [
      'C of O',
      'Survey Plan',
      'Deed of Assignment',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033445566' },
      { type: 'phone', label: 'Call Direct', value: '+2348033445566' },
    ],
  },

  {
    _id: 'land-2',
    _type: 'listing',
    _createdAt: '2026-08-10T08:00:00Z',
    title: '1,000 sqm Waterfront Residential Plot in Banana Island, Ikoyi',
    slug: { current: 'waterfront-residential-plot-banana-island' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-2', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Exclusive waterfront land parcel within Banana Island enclave. Direct lagoon frontage with underground utilities, paved roads, and elite gated security. Federal C of O.`,
    price: 1200000000,
    priceOnRequest: false,
    location: { city: 'Banana Island, Ikoyi', state: 'Lagos' },
    status: 'available',
    plots: 1.6,
    landSizeSqm: 1000,
    landPurpose: 'sale',
    features: [
      { label: 'Direct Lagoon Frontage', icon: 'waterfront' },
      { label: 'Underground Utilities', icon: 'infrastructure' },
      { label: 'Elite Gated Estate', icon: 'security' },
    ],
    documents: [
      'Federal C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055667788' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348055667788' },
    ],
  },

  {
    _id: 'land-3',
    _type: 'listing',
    _createdAt: '2026-08-08T14:00:00Z',
    title: '600 sqm Dry Residential Plot in Gated Estate, Bogije Ibeju-Lekki',
    slug: { current: '600-sqm-dry-plot-bogije-ibeju-lekki' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-3', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `100% table dry land ready for immediate building. Gated community with perimeter fencing, security gatehouse, and paved access. Gazette title with no community disputes.`,
    price: 28000000,
    priceOnRequest: false,
    location: { city: 'Bogije', state: 'Lagos' },
    status: 'available',
    plots: 1,
    landSizeSqm: 600,
    landPurpose: 'sale',
    features: [
      { label: '100% Dry Ground', icon: 'dry-land' },
      { label: 'Gated Estate with Gatehouse', icon: 'security' },
      { label: 'Immediate Allocation', icon: 'landmark' },
    ],
    documents: [
      'Gazette',
      'Registered Survey',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011228899' },
      { type: 'phone', label: 'Call Direct', value: '+2348011228899' },
    ],
  },

  {
    _id: 'land-4',
    _type: 'listing',
    _createdAt: '2026-08-06T11:30:00Z',
    title: '1,200 sqm Hilltop Plot with Approved Building Plan, Guzape Abuja',
    slug: { current: '1200-sqm-hilltop-plot-guzape-abuja' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-4', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Prime residential double plot in Guzape District overlooking the central city. Fully surveyed with ready FCDA building approvals for two semi-detached units. Right of Occupancy (R of O).`,
    price: 140000000,
    priceOnRequest: false,
    location: { city: 'Guzape Hills', state: 'Abuja' },
    status: 'available',
    plots: 2,
    landSizeSqm: 1200,
    landPurpose: 'sale',
    features: [
      { label: 'Hilltop Panoramic View', icon: 'view' },
      { label: 'Tarred Access Road', icon: 'road' },
      { label: 'Approved FCDA Plan', icon: 'infrastructure' },
    ],
    documents: [
      'R of O',
      'Survey Plan',
      'FCDA Building Approval',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099223344' },
      { type: 'phone', label: 'Call Land Desk', value: '+2348099223344' },
    ],
  },

  {
    _id: 'land-5',
    _type: 'listing',
    _createdAt: '2026-08-04T09:00:00Z',
    title: '5 Hectares Mixed-Use Development Land near Alaro City Axis, Epe',
    slug: { current: '5-hectares-mixed-use-alaro-city-epe' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-5', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Strategic large parcel suitable for private residential estate, university campus, medical city, or commercial logistics depot. Flat dry terrain near proposed Lekki International Airport.`,
    price: 650000000,
    priceOnRequest: false,
    location: { city: 'Epe / Alaro City Axis', state: 'Lagos' },
    status: 'available',
    plots: 75,
    landSizeSqm: 50000,
    landPurpose: 'sale',
    features: [
      { label: '5 Hectares Multi-Plot Size', icon: 'dry-land' },
      { label: 'Near International Airport Axis', icon: 'landmark' },
      { label: 'Dual Expressway Access', icon: 'road' },
    ],
    documents: [
      'C of O',
      'Perimeter Survey',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077551122' },
      { type: 'phone', label: 'Call Executive Desk', value: '+2348077551122' },
    ],
  },

  {
    _id: 'land-6',
    _type: 'listing',
    _createdAt: '2026-08-02T15:15:00Z',
    title: '2 Acres (12 Plots) Industrial Land Parcel in Idu Industrial, Abuja',
    slug: { current: '2-acres-industrial-land-idu-abuja' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-6', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Zoned industrial parcel with direct high-tension electricity access and proximity to Idu Railway Terminal. Perfect for manufacturing plant, warehouse hub, or fabrication yard.`,
    price: 180000000,
    priceOnRequest: false,
    location: { city: 'Idu Industrial Zone', state: 'Abuja' },
    status: 'available',
    plots: 12,
    landSizeSqm: 8100,
    landPurpose: 'sale',
    features: [
      { label: 'Industrial Zoning Approved', icon: 'infrastructure' },
      { label: 'High-Tension Power Lines', icon: 'electricity' },
      { label: 'Proximity to Railway Terminal', icon: 'landmark' },
    ],
    documents: [
      'C of O',
      'Industrial Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033991122' },
      { type: 'phone', label: 'Call Direct', value: '+2348033991122' },
    ],
  },

  {
    _id: 'land-7',
    _type: 'listing',
    _createdAt: '2026-07-31T12:00:00Z',
    title: '650 sqm Commercial Corner Plot on Ring Road, Ibadan',
    slug: { current: '650-sqm-commercial-plot-ring-road-ibadan' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-7', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `High-commercial density corner plot on Ring Road. Ideal for banking branch, retail shopping complex, fast-food franchise, or pharmacy chain. Registered conveyance and survey.`,
    price: 38000000,
    priceOnRequest: false,
    location: { city: 'Ring Road', state: 'Ibadan' },
    status: 'available',
    plots: 1.1,
    landSizeSqm: 650,
    landPurpose: 'sale',
    features: [
      { label: 'High Traffic Commercial Hub', icon: 'road' },
      { label: 'Corner Piece Position', icon: 'corner' },
      { label: 'Electricity Connected', icon: 'electricity' },
    ],
    documents: [
      'Deed of Conveyance',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348088334411' },
      { type: 'phone', label: 'Call Owner', value: '+2348088334411' },
    ],
  },

  {
    _id: 'land-8',
    _type: 'listing',
    _createdAt: '2026-07-28T10:00:00Z',
    title: '1,500 sqm Prime Commercial Land on Airport Road, Port Harcourt',
    slug: { current: '1500-sqm-commercial-land-airport-road-ph' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-8', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Fenced 1,500 sqm commercial parcel along Airport Road corridor. High traffic exposure suitable for hotel, corporate regional office, or multi-story plaza. Rivers State C of O.`,
    price: 290000000,
    priceOnRequest: false,
    location: { city: 'Airport Road', state: 'Port Harcourt' },
    status: 'available',
    plots: 2.5,
    landSizeSqm: 1500,
    landPurpose: 'sale',
    features: [
      { label: 'Expressway Frontage', icon: 'road' },
      { label: 'Perimeter Block Fencing', icon: 'fence' },
      { label: 'Commercial Zoning', icon: 'infrastructure' },
    ],
    documents: [
      'Rivers State C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348055118899' },
      { type: 'phone', label: 'Call Direct', value: '+2348055118899' },
    ],
  },

  {
    _id: 'land-9',
    _type: 'listing',
    _createdAt: '2026-07-25T14:30:00Z',
    title: '2 Hectares Agricultural Land Parcel with Natural Stream, Epe/Ogun Border',
    slug: { current: '2-hectares-farmland-epe-border' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-9', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Rich arable farmland with perennial water source stream. Ideal for mechanized crop cultivation, poultry farm, greenhouse, or agro-processing factory. Motorized access road.`,
    price: 22000000,
    priceOnRequest: false,
    location: { city: 'Erunwon, Epe Axis', state: 'Lagos' },
    status: 'available',
    plots: 30,
    landSizeSqm: 20000,
    landPurpose: 'sale',
    features: [
      { label: 'Natural Stream Water Source', icon: 'waterfront' },
      { label: 'Fertile Arable Soil', icon: 'dry-land' },
      { label: 'Motorable Access Road', icon: 'road' },
    ],
    documents: [
      'Registered Family Deed',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348011447788' },
      { type: 'phone', label: 'Call Farm Desk', value: '+2348011447788' },
    ],
  },

  {
    _id: 'land-10',
    _type: 'listing',
    _createdAt: '2026-07-22T11:00:00Z',
    title: '1,000 sqm Residential Plot in Diplomats Enclave, Maitama Extension',
    slug: { current: '1000-sqm-plot-maitama-extension' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-10', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `High-prestige residential plot in Maitama Extension with complete underground infrastructure, asphalt access roads, and streetlights. Direct allocation with FCDA C of O.`,
    price: 320000000,
    priceOnRequest: false,
    location: { city: 'Maitama Extension', state: 'Abuja' },
    status: 'available',
    plots: 1.6,
    landSizeSqm: 1000,
    landPurpose: 'sale',
    features: [
      { label: 'Diplomatic Gated Zone', icon: 'security' },
      { label: 'Underground Infrastructure', icon: 'infrastructure' },
      { label: 'Paved Asphalt Road', icon: 'road' },
    ],
    documents: [
      'FCDA C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099665544' },
      { type: 'phone', label: 'Call Direct', value: '+2348099665544' },
    ],
  },

  {
    _id: 'land-11',
    _type: 'listing',
    _createdAt: '2026-07-19T13:45:00Z',
    title: '600 sqm Serviced Plot with Instant Allocation, Mowe-Ofada Corridor',
    slug: { current: '600-sqm-serviced-plot-mowe-ofada' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-11', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Affordable dry plot in a developed residential scheme. Security, drainage, transformer on site, and instant allocation upon payment. C of O in process.`,
    price: 14500000,
    priceOnRequest: false,
    location: { city: 'Mowe Corridor', state: 'Ogun' },
    status: 'available',
    plots: 1,
    landSizeSqm: 600,
    landPurpose: 'sale',
    features: [
      { label: 'Transformer On Site', icon: 'electricity' },
      { label: 'Instant Allocation', icon: 'landmark' },
      { label: 'Dry Level Ground', icon: 'dry-land' },
    ],
    documents: [
      'Registered Survey',
      'Deed of Assignment',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077229988' },
      { type: 'phone', label: 'Call Direct', value: '+2348077229988' },
    ],
  },

  {
    _id: 'land-12',
    _type: 'listing',
    _createdAt: '2026-07-16T15:00:00Z',
    title: '3 Plots (1,800 sqm) Waterfront Commercial Land, VGC Lekki',
    slug: { current: 'waterfront-commercial-land-vgc-lekki' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-12', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Lagoon-front commercial block near Victoria Garden City (VGC) main gate. High vehicular visibility, paved boulevard access, and lagoon view. Governor's Consent.`,
    price: 220000000,
    priceOnRequest: false,
    location: { city: 'VGC Axis', state: 'Lagos' },
    status: 'available',
    plots: 3,
    landSizeSqm: 1800,
    landPurpose: 'sale',
    features: [
      { label: 'Waterfront Frontage', icon: 'waterfront' },
      { label: 'Paved Boulevard Access', icon: 'road' },
      { label: 'High Commercial Value', icon: 'landmark' },
    ],
    documents: [
      "Governor's Consent",
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348033115599' },
      { type: 'phone', label: 'Call Direct', value: '+2348033115599' },
    ],
  },

  {
    _id: 'land-13',
    _type: 'listing',
    _createdAt: '2026-07-13T10:30:00Z',
    title: '800 sqm Serviced Estate Plot in Centenary City, Enugu',
    slug: { current: '800-sqm-plot-centenary-city-enugu' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-13', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Well-planned residential plot in Centenary City Enugu with wide concrete access roads, underground storm drainage, perimeter security fencing, and street lighting.`,
    price: 45000000,
    priceOnRequest: false,
    location: { city: 'Centenary City', state: 'Enugu' },
    status: 'available',
    plots: 1.3,
    landSizeSqm: 800,
    landPurpose: 'sale',
    features: [
      { label: 'Underground Storm Drainage', icon: 'infrastructure' },
      { label: 'Concrete Road Network', icon: 'road' },
      { label: 'Gated Security Estate', icon: 'security' },
    ],
    documents: [
      'C of O',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348066881122' },
      { type: 'phone', label: 'Call Direct', value: '+2348066881122' },
    ],
  },

  {
    _id: 'land-14',
    _type: 'listing',
    _createdAt: '2026-07-10T08:45:00Z',
    title: '10 Hectares Agro-Allied & Logistics Parcel near Moniya Dry Port Axis',
    slug: { current: '10-hectares-logistics-parcel-moniya' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-14', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Massive 10-hectare flat land parcel adjacent to the new Lagos-Ibadan rail line corridor in Moniya. Ideal for bonded terminal, container depot, grain silos, or food processing factory.`,
    price: 95000000,
    priceOnRequest: false,
    location: { city: 'Moniya Axis', state: 'Ibadan' },
    status: 'available',
    plots: 150,
    landSizeSqm: 100000,
    landPurpose: 'sale',
    features: [
      { label: 'Proximity to Railway Corridor', icon: 'landmark' },
      { label: '100% Flat Dry Ground', icon: 'dry-land' },
      { label: 'Logistics Depot Zoning', icon: 'infrastructure' },
    ],
    documents: [
      'Oyo State Gazette',
      'Perimeter Survey',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348044118833' },
      { type: 'phone', label: 'Call Direct', value: '+2348044118833' },
    ],
  },

  {
    _id: 'land-15',
    _type: 'listing',
    _createdAt: '2026-07-07T14:15:00Z',
    title: '500 sqm Dry Residential Corner Plot on Orchid Road, Lekki',
    slug: { current: '500-sqm-corner-plot-orchid-road' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-15', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Corner piece residential land in fully developed neighborhood on Orchid Road. Ready for duplex or terrace construction. Governor's consent.`,
    price: 52000000,
    priceOnRequest: false,
    location: { city: 'Orchid Road, Lekki', state: 'Lagos' },
    status: 'available',
    plots: 0.8,
    landSizeSqm: 500,
    landPurpose: 'sale',
    features: [
      { label: 'Corner Piece Plot', icon: 'corner' },
      { label: 'Paved Access Road', icon: 'road' },
      { label: 'Dry Land with Drainage', icon: 'dry-land' },
    ],
    documents: [
      "Governor's Consent",
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348022774488' },
      { type: 'phone', label: 'Call Direct', value: '+2348022774488' },
    ],
  },

  {
    _id: 'land-16',
    _type: 'listing',
    _createdAt: '2026-07-04T11:00:00Z',
    title: '2,500 sqm Commercial Plot near Abuja-Keffi Expressway (Lease)',
    slug: { current: 'commercial-plot-abuja-keffi-expressway' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-16', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Paved open commercial land suitable for truck park, building material depot, auto repair workshop, or event center. Fenced on three sides. Long lease available.`,
    price: 12000000,
    priceOnRequest: false,
    location: { city: 'Karu Corridor', state: 'Nasarawa' },
    status: 'available',
    plots: 4.1,
    landSizeSqm: 2500,
    landPurpose: 'lease',
    features: [
      { label: 'Direct Expressway Visibility', icon: 'road' },
      { label: 'Heavy Truck Access', icon: 'infrastructure' },
      { label: 'Commercial Lease', icon: 'landmark' },
    ],
    documents: [
      'Commercial Lease Agreement',
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348099553311' },
      { type: 'phone', label: 'Call Direct', value: '+2348099553311' },
    ],
  },

  {
    _id: 'land-17',
    _type: 'listing',
    _createdAt: '2026-07-01T09:00:00Z',
    title: '1,200 sqm Waterfront Plot with Governor\'s Consent, Sangotedo Lekki',
    slug: { current: '1200-sqm-waterfront-plot-sangotedo' },
    category: 'land',
    coverImage: {
      _type: 'image',
      asset: { _ref: 'image-land-17', _type: 'reference' },
      url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    },
    gallery: [],
    description: `Serene waterfront land plot directly on the canal with private jetty potential. Gated estate, paved roads, and electricity. Perfect for private retreat villa or block of luxury apartments.`,
    price: 185000000,
    priceOnRequest: false,
    location: { city: 'Sangotedo', state: 'Lagos' },
    status: 'available',
    plots: 2,
    landSizeSqm: 1200,
    landPurpose: 'sale',
    features: [
      { label: 'Direct Water Canal Frontage', icon: 'waterfront' },
      { label: 'Gated Security Estate', icon: 'security' },
      { label: 'Governor\'s Consent Title', icon: 'landmark' },
    ],
    documents: [
      "Governor's Consent",
      'Survey Plan',
    ],
    contactLinks: [
      { type: 'whatsapp', label: 'Chat on WhatsApp', value: '2348077331144' },
      { type: 'phone', label: 'Call Direct', value: '+2348077331144' },
    ],
  },
]
